import { Role } from '@erplms/types';

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, string[]> = {
  SUPER_ADMIN: ['*'],
  NCCT_ADMIN: ['*'],
  INSTITUTION_ADMIN: [
    'org:*',
    'programme:*',
    'nomination:*',
    'batch:*',
    'trainee:*',
    'trainer:*',
    'timetable:*',
    'hostel:*',
    'logistics:*',
    'attendance:*',
    'lms:*',
    'assessment:*',
    'skills:*',
    'certificate:*',
    'job:*',
    'analytics:*',
    'document:*',
    'audit:*',
    'department:*',
    'academic:*',
    'course:*',
    'faculty:*',
    'student:*',
    'grade:*',
  ],
  COORDINATOR: [
    'org:read',
    'programme:read',
    'programme:edit',
    'nomination:*',
    'batch:*',
    'trainee:read',
    'trainee:create',
    'trainer:read',
    'timetable:*',
    'hostel:*',
    'logistics:*',
    'attendance:*',
    'lms:read',
    'certificate:*',
    'analytics:institution',
    'document:read',
    'document:upload',
  ],
  TRAINER: [
    'programme:read',
    'batch:read',
    'trainee:read',
    'timetable:read',
    'session:read',
    'attendance:create',
    'attendance:mark',
    'attendance:read',
    'lms:read',
    'lms:create',
    'lms:edit',
    'lms:grade',
    'assessment:*',
    'skills:*',
    'certificate:read',
    'document:read',
    'document:upload',
    // legacy
    'course:read',
    'faculty:read',
    'student:read',
    'grade:create',
    'grade:read',
  ],
  TRAINEE: [
    'trainee:read:own',
    'trainee:update:own',
    'programme:read',
    'nomination:create:self',
    'programme:register',
    'timetable:read:own',
    'session:read:own',
    'attendance:read:own',
    'attendance:mark:qr',
    'lms:read:enrolled',
    'lms:submit',
    'offline:sync',
    'assessment:attempt',
    'skills:read:own',
    'certificate:read:own',
    'job:read',
    'job:apply',
    'career:chat',
    'analytics:trainee',
    'document:read:own',
    // legacy
    'student:read:own',
    'course:read:enrolled',
    'grade:read:own',
  ],
  EMPLOYER: [
    'job:*',
    'application:*',
    'candidate:search',
    'candidate:read',
    'certificate:verify',
    'analytics:employer',
  ],
  PRINCIPAL: [
    'org:read',
    'department:read',
    'academic:read',
    'course:read',
    'faculty:read',
    'student:read',
    'attendance:read',
    'attendance:approve',
    'lms:read',
    'assessment:read',
    'grade:read',
    'grade:publish',
    'analytics:*',
    'document:read',
    'audit:read',
  ],
  HOD: [
    'department:read',
    'academic:read',
    'academic:create',
    'course:read',
    'course:create',
    'course:edit',
    'course:allocate',
    'faculty:read',
    'student:read',
    'attendance:read',
    'attendance:approve',
    'lms:read',
    'lms:create',
    'assessment:read',
    'assessment:create',
    'grade:read',
    'grade:publish',
    'analytics:department',
    'document:read',
  ],
  FACULTY: [
    'course:read',
    'student:read',
    'attendance:create',
    'attendance:mark',
    'attendance:read',
    'lms:read',
    'lms:create',
    'lms:edit',
    'lms:grade',
    'assessment:create',
    'assessment:grade',
    'grade:create',
    'grade:read',
    'analytics:faculty',
    'document:read',
    'document:upload',
  ],
  STUDENT: [
    'student:read:own',
    'course:read:enrolled',
    'attendance:read:own',
    'lms:read:enrolled',
    'lms:submit',
    'grade:read:own',
    'analytics:student',
    'document:read:own',
  ],
  PARENT: [
    'student:read:child',
    'attendance:read:child',
    'grade:read:child',
    'analytics:student',
  ],
  STAFF: [
    'student:read',
    'attendance:read',
    'document:read',
  ],
  FINANCE: [
    'finance:*',
    'student:read',
  ],
  HR: [
    'faculty:*',
    'staff:*',
  ],
  LIBRARIAN: [
    'library:*',
    'student:read',
    'faculty:read',
  ],
};

export function hasPermission(userPermissions: string[], required: string): boolean {
  if (userPermissions.includes('*')) {
    return true;
  }

  const [reqCategory] = required.split(':');
  if (userPermissions.includes(`${reqCategory}:*`)) {
    return true;
  }

  return userPermissions.includes(required);
}
